# Generated by Django 4.2.13 on 2024-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(verbose_name='Service date'),
        ),
    ]
