# Generated by Django 4.2.13 on 2024-06-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_service_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
    ]
